//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string ImageUrl { get; set; }
        public string VideoUrl { get; set; }
        public string ButtonText { get; set; }
        public string ButtonLink { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
    }
}
